version: "3.1"
services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_CONTAINER_IMAGE_NAME}
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${postgres_PASS}
      - POSTGRES_USER=${postgres_USER}
      - POSTGRES_DB=${postgres_DB}
    ports:
      - ${postgres_PORT}:5432
    volumes:
      - ./data_postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: ${PGADMIN_CONTAINER_IMAGE_NAME}
    restart: always
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80