version: "3.1"
services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_CONTAINER_IMAGE_NAME}
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${postgres_PASS}
      - POSTGRES_USER=${postgres_USER}
      - POSTGRES_DB=${postgres_DB}
    ports:
      - ${postgres_PORT}:5432
    volumes:
      - ./data_postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: ${PGADMIN_CONTAINER_IMAGE_NAME}
    restart: "no"
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
  
  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql
    restart: "no"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: ${PMA_CONTAINER_NAME}
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
      - ${PMA_PORT}:80
    env_file:
      - .env
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${PMA_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}